### ISSUE TITLE
Some question about "custom terrain in Gazebo simulation"

### ISSUE THREAD

**Issue by coding9991** [sdwyc/sim_environment_arranger#1]
First of all, thank you very much for your open source work. I am also working on autonomous navigation on uneven terrain
- Q1
 I am very curious about how you generate custom terrain(.dea file) in Gazebo? I have been struggling with this issue for a long time.
- Q2
 My custom terrain often causes the robot model to fly away after being placed on it. I suspect that the problem is with the inertia settings. Have you encountered similar issues during the development process? Could you provide some guidance or information to help me out? 

I am looking forward to your reply.
Best regards

**Comment by sdwyc** [comment]
Hi! Thanks for your attention. I will share my experience at first with respect to your questions.
Q1: The .dae files are created by Blender, which is a useful and simple 3d model software. This is the page of software: https://www.blender.org/
Q2: Yes, I did have encounter this problem. The cause is gravity is not set. You check your project whether turn on the gravity function in model description files. (Tips: This is only one scenario I encountered, maybe exists other cause.)
I hope these experience is useful for you.
